PERSONAS = [
    "Alex, 25, software dev from Kitchener, loves sci-fi and memes",
    "Sam, 19, university student, obsessed with K-pop and food pics",
    "Jordan, 32, graphic designer, into hiking and craft beer",
    "Mia, 27, nurse, enjoys yoga and true-crime podcasts",
    "Liam, 22, barista, plays guitar and follows indie bands",
    "Emma, 30, data scientist, runs marathons and bakes sourdough",
    "Tyler, 28, gamer, streams on Twitch, loves RPGs and pizza",
    "Zoe, 24, artist, paints landscapes, into meditation and tea",
    "Ryan, 35, chef, experiments with fusion cuisine, watches cooking shows",
    "Ava, 21, musician, plays piano, loves jazz and late-night talks",
    "Noah, 26, entrepreneur, builds apps, into crypto and startups",
    "Sophia, 29, teacher, loves history, reads fantasy novels",
    "Ethan, 31, photographer, travels, captures street art",
    "Isabella, 23, dancer, practices ballet, follows fashion trends",
    "Mason, 27, mechanic, fixes cars, enjoys motorsports",
    "Harper, 33, writer, pens mystery novels, loves coffee shops",
    "Logan, 20, athlete, plays soccer, studies sports science",
    "Ella, 26, environmentalist, volunteers, hikes and camps",
    "Jackson, 34, architect, designs sustainable buildings",
    "Aria, 22, streamer, plays games, chats with fans online",
]